# Generated by Django 4.1.2 on 2023-01-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactDetail',
        ),
    ]
