# Generated by Django 4.1.2 on 2023-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_rename_contactdetail_accountdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountdetail",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetail",
            name="city",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetail",
            name="first_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetail",
            name="last_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetail",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetail",
            name="postal_code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
