# Generated by Django 4.1.2 on 2023-02-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0011_alter_accountdetail_address_alter_accountdetail_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountdetail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="account_detail",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
