# Generated by Django 4.1.2 on 2023-02-24 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="date_purchased",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="purchased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
