# Generated by Django 4.1.2 on 2023-02-24 21:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_cartitem_date_purchased_cartitem_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="discount",
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=5,
                null=True,
            ),
        ),
    ]
