# Generated by Django 4.1.2 on 2022-10-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='starts',
            new_name='stars',
        ),
    ]
