# Generated by Django 4.1.2 on 2023-02-24 22:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_cartitem_discount_product_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
