# Generated by Django 4.1.2 on 2022-10-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_starts_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_counter',
            field=models.IntegerField(default=0),
        ),
    ]
