# Generated by Django 4.1.2 on 2022-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_product_visit_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="home.tag"),
        ),
    ]
