# Generated by Django 4.1.2 on 2023-02-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_product_discount_product_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
