# Generated by Django 4.1.7 on 2023-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "P"),
                    ("PROCESSING", "PO"),
                    ("SHIPPED", "SH"),
                    ("DELIVERED", "DE"),
                    ("CANCELLED", "CA"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
