# Generated by Django 4.1.2 on 2022-12-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="product",
            new_name="products",
        ),
    ]
