# Generated by Django 4.1.2 on 2023-01-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_product_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
